profiles/urls.py
from django.conf.urls import url
from views import UserDetail, new_user

urlpatterns = [
    url(r'^detail/(?P<pk>\w+)/$', UserDetail.as_view(), name='user_detail'),
    url(r'^new/$', new_user, name="new_user"),
]

profiles_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from profiles.views import UserDetail, UserList, HomeView
from rest_framework import routers
from profiles.api import UserViewSet, GroupViewSet
from profiles.api import ProfileAddressViewSet, ProfileMediaViewSet, ProfileUserViewSet


router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)

profile_router = routers.DefaultRouter()
profile_router .register(r'usuarios', ProfileUserViewSet)
profile_router .register(r'medias', ProfileMediaViewSet)
profile_router .register(r'direcciones', ProfileAddressViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', HomeView.as_view(), name='home'),

    # URL de mi app "profile"
    url(r'^user/', include('profiles.urls')),
    # ---------------------------------------------
    # API REST
    url(r'^', include(router.urls)),  # para ver los user y grupos

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^', include(profile_router.urls)),  # para ver los usuarios , direcciones y medias
    # ---------------------------------------------

    #  url(r'^users/$', UsersView.as_view(), name='all_user_template'),  # ahora no me sirve
    url(r'^users_list/$', UserList.as_view(), name='all_user_list'),
]

profiles/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.exceptions import ValidationError


class Address(models.Model):
    STATE_CHOICES = (
        (None, '(Seleccione)'),
        (1, 'Buenos Aires'),
        (2, 'Buenos Aires-GBA'),
        (3, 'Capital Federal'),
        (4, 'Catamarca'),
        (5, 'Chaco'),
        (6, 'Chubut'),
        (7, 'Córdoba'),
        (8, 'Corrientes'),
        (9, 'Entre Ríos'),
        (10, 'Formosa'),
        (11, 'Jujuy'),
        (12, 'La Pampa'),
        (13, 'La Rioja'),
        (14, 'Mendoza'),
        (15, 'Misiones'),
        (16, 'Neuquén'),
        (17, 'Río Negro'),
        (18, 'Salta'),
        (19, 'San Juan'),
        (20, 'San Luis'),
        (21, 'Santa Cruz'),
        (22, 'Santa Fe'),
        (23, 'Santiago del Estero'),
        (24, 'Tierra del Fuego'),
        (25, 'Tucumán')
    )
    address = models.CharField(
        "Direccion", max_length=50, blank=False, null=False)
    city = models.CharField("Ciudad", max_length=50, blank=False, null=False)
    state = models.IntegerField(
        "Provincia", choices=STATE_CHOICES, blank=False, null=False)
    country = models.CharField("Pais", max_length=50, blank=False, null=False)
    zip_code = models.IntegerField("Cod Postal", blank=False, null=False)

    class Meta:
        verbose_name_plural = "Addresses"

    def __str__(self):
        return "{}".format(self.address)

    def get_address(self):
        return self.address


class User(models.Model):

    GENDER_CHOICES = (
        ("M", 'Hombre'),
        ("F", 'Mujer'),  # code --> (DB, label)
    )

    first_name = models.CharField(
        "Nombre", max_length=50, blank=False, null=False)
    last_name = models.CharField(
        "Apellido", max_length=50, blank=False, null=False)
    gender = models.CharField(
        "Genero",
        max_length=2,
        choices=GENDER_CHOICES,
        default="M",
        blank=False,
        null=False,
        help_text='Solamente existen 2 géneros',
    )
    email = models.EmailField(blank=False, null=False,
                              help_text="Ejemplo: usuario@mail.com")
    phone = models.IntegerField(blank=True, null=True)
    active = models.BooleanField("Activo", default=False)
    fecha_alta = models.DateTimeField(
        'Fecha de Creacion', auto_now=False, auto_now_add=True, null=False, blank=False)
    fecha_modificacion = models.DateTimeField(
        auto_now=True, editable=False, null=False, blank=False)
    # auto_now_add=False --> exclusivo con auto_now
    address = models.ForeignKey(Address)  # un User tiene una sola direccion

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return "{}, {}".format(self.last_name, self.first_name)

    def clean_first_name(self):
        name = self.first_name

        if len(name) < 2:
            raise ValidationError("Ingrese un nombre con mas de 2 caracteres")
        else:
            self.first_name = name.title()

    def clean_last_name(self):
        name = self.last_name

        if len(name) < 2:
            raise ValidationError(
                "Ingrese un apellido con mas de 2 caracteres")
        else:
            self.last_name = name.title()

    def clean_email(self):
        email = self.email

        if email == '':
            raise ValidationError("Ingrese un email")
        else:
            base, prov = email.split("@")
        # dom, ext = prov.split(".")

        if not prov.lower() == "gmail.com":
            raise ValidationError("Por favor utilice una cuenta de Gmail")
        else:
            self.email = email.lower()

    def clean(self):
        self.clean_last_name()
        self.clean_first_name()
        self.clean_email()

    def total_social_medias(self):
        total = self.media_set.all().count()
        # total = Media.objects.filter(user_id=self.id).count()
        return total

    total_social_medias.short_description = '# Redes'

    #  Nombre de la columna en el Admin

    def sex(self):
        if self.gender == "M":
            return "H"
        return "F"


class Media(models.Model):
    name = models.CharField(max_length=50, blank=False,
                            null=False, help_text='Ej: Facebook Cuenta Oficial')
    url = models.URLField(blank=False, null=False,
                          help_text='Ej: https://es-la.facebook.com/leomessi/')
    user_id = models.ForeignKey(User)

    def __str__(self):
        return self.name

profiles/forms.py
from django import forms
from models import User, Address, Media
from django.core.exceptions import ValidationError


class UserModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["last_name", "first_name", "gender", "email", "phone", "active"]
        exclude = ["fecha_alta", "fecha_modificacion"]

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if not email.endswith('gmail.com'):
            raise ValidationError("Invalid email address.")

        return email


class AddressModelForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ["country", "state", "city", "address", "zip_code"]


class MediaModelForm(forms.ModelForm):
    class Meta:
        model = Media
        fields = ['name', 'url']

profiles/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic import TemplateView, DetailView, ListView
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from .models import User, Media
from forms import UserModelForm, AddressModelForm
from django.forms import modelformset_factory


# def all_user(request):
#     todos = User.objects.all()
#     context = {
#         'todos': todos
#     }
#
#     return render(request, 'profiles/users.html', context)
class HomeView(TemplateView):
    """ solamente renderiza el template """
    template_name = "profiles/home_view.html"


# class UsersView(TemplateView):
#     model = User
#     # template_name = "profiles/users.html"
#
#     def get_context_data(self, *args, **kwargs):
#         context = super(UsersView, self).get_context_data(*args, **kwargs)
#         context['todos'] = User.objects.all()
#         return context
#  no lo uso xq realmente quiero una lista de usuer, lo hago abajo con 2 lineas


class UserList(ListView):
    model = User
    # template es user_list.html
    context_object_name = 'the_best_users'
    # object_list por defecto


class UserDetail(DetailView):
    model = User

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(UserDetail, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['media_list'] = Media.objects.filter(user_id=self.kwargs['pk'])  # Media.objects.all()
        print type(context)
        return context


def new_user(request):

    MediaFormSet = modelformset_factory(Media, fields=('name', 'url'), max_num=3, extra=2)

    # media_form = MediaFormSet(queryset=Media.objects.none())

    if request.method == "POST":
        address_form = AddressModelForm(request.POST)
        user_form = UserModelForm(request.POST)
        media_form = MediaFormSet(request.POST)

        if address_form.is_valid() and user_form.is_valid() and media_form.is_valid():

            address = address_form.save()
            user = user_form.save(commit=False)
            user.address = address
            user.save()

            media = media_form.save(commit=False)

            for el in media:
                el.user_id = user
                el.save()

            messages.success(request, "Usuario '{}' creado".format(user.email))
            # return redirect(reverse('all_user_list'))
        else:
            messages.error(request, 'Verifique los campos')
    else:
        address_form = AddressModelForm()
        user_form = UserModelForm()
        media_form = MediaFormSet(queryset=Media.objects.none())
    context = {
        'user_form': user_form,
        'address_form': address_form,
        'media_form': media_form,
    }

    return render(request, "profiles/user_new3.html", context)

# def new_user(request):
#     if request.method == "POST":
#         address_form = AddressModelForm(request.POST)
#         user_form = UserModelForm(request.POST)
#
#         if address_form.is_valid() and user_form.is_valid():
#             address = address_form.save()
#             user = user_form.save(commit=False)
#             user.address = address
#             user.save()
#
#             messages.success(request, "Usuario '{}' creado".format(user.email))
#             # return redirect(reverse('all_user_list'))
#         else:
#             messages.error(request, 'Verifique los campos')
#     else:
#         address_form = AddressModelForm()
#         user_form = UserModelForm()
#
#     context = {
#         'user_form': user_form,
#         'address_form': address_form,
#     }
#
#     return render(request, "profiles/user_new2.html", context)
#

# OBSOLETO AHORA USO 2 MODEL IN 1 FORM
# def new_user1(request):
#
#     form = UserModelForm(request.POST or None)
#     context = {
#         'form': form
#     }
#
#     if form.is_valid():
#         instance = form.save(commit=False)
#         # timezone.now() no es necesario
#         instance.save()
#         context = {
#             'form': form
#     return render(request, "profiles/user_new2.html", context)
#         }

profiles/templates/profiles/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="{% static 'profiles/js/bootstrap.min.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'profiles/css/bootstrap.min.css' %}" >

  {% block title %}
  {% endblock %}

</head>
  <body >

    {% include "profiles/includes/navbar.html" %}

    <div class="container">
      <br>
      {% block content %}
      {% endblock %}

    </div>

  </body>


</html>

profiles/templates/profiles/home_view.html
{% extends 'profiles/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title>Mi pobre home</title>
{% endblock %}


{% block content%}
<div class="jumbotron jumbotron-fluid">
  	<div class="container">
	      <h1 class="display-4">My Django Crash Curse!</h1>
	      <p class="lead">Simple Jumbotron con BS 4 :D </p>
	      <hr class="my-4">
	      <p>Bienvenido Usuario</p>
	      <a class="btn btn-primary btn-lg" href="{% url 'new_user' %}" role="button">Crear Usuario</a>
	</div>
</div>
{% endblock%}

profiles/templates/profiles/user_detail.html
{% extends 'profiles/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title>Detail</title>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-6">

<div class="card text-white bg-primary mb-3" style="max-width: 30rem;">
  <div class="card-header">Detalle de User</div>
  <div class="card-body">
    <h5 class="card-title">{{ object.last_name}}, {{object.first_name}}</h5>
    <ul>
      <li>ID: {{object.id}}</li>
      <li>Email: {{ object.email }}</li>
      <li>Phone: {{ object.phone }}</li>
      <li>Country: {{ object.address.country }}</li>
      <li>State: {{ object.address.get_state_display }}</li>
      <li>City: {{ object.address.city }}</li>
      <li>Address: {{ object.address.address }}</li>
      <li>Fecha Creacion: {{ object.fecha_alta }}</li>
      <li>Active: {{ object.active }}</li>

    </ul>
  </div>
  </div>
  </div>

  <div class="col-sm-6">



  <div class="card text-white bg-dark mb-3" style="max-width: 60rem;">
    <div class="card-header">Redes Sociales</div>
      <div class="card-body">

        {% if media_list%}
        <ul>

          {%for social in media_list%}
            <li>{{social.name}}: <a href="{{ el.url }}">{{ social.url }}</a></li>

          <br>
          {%endfor%}

        </ul>
        {%else%}
        <ul>
          <li>Ninguna</li>
        </ul>
        {%endif%}
  </div>
  </div>
  </div>

</div>

{% endblock %}

profiles/templates/profiles/user_list.html
{% extends 'profiles/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title>User List</title>
{% endblock %}

{% block content %}
    <h1>Listado de todos los User =D </h1>
    <h4>Estoy usando List View</h4>

<div class="table-responsive-md">
<table class="table" style="width:100%">
  <thead class="thead-dark">
  <tr>
    <th scope="col">Email</th>
    <th scope="col">Full Name</th>
    <th scope="col"># Medias</th>
    <th scope="col">Phone</th>
    <th scope="col">Gender</th>
    <th scope="col">State</th>
    <th scope="col">Active ?</th>
  </tr>
  </thead>
    <tbody>
    {% for unUser in the_best_users %}
        <tr>

	        <th scope="row">{{unUser.email}}</th>
            <td> <a href = "{% url 'user_detail' unUser.id %}">{{unUser}}</td>
            <td>{{unUser.total_social_medias}}</td>
            <td>{{unUser.phone}}</td>
            <td>{{unUser.get_gender_display}}</td>
            <td>{{unUser.address.get_state_display}}</td>
            <td>{{unUser.active}}</td>
	    </tr>
    {% endfor %}
</tbody>
</table>
</div>
{%endblock%}

profiles/templates/profiles/user_new3.html
{% extends 'profiles/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title>New User</title>
{% endblock %}

{% block content %}

    {% for hidden_field in user_form.hidden_fields %}
        {{ hidden_field }}
    {% endfor %}

<div class="container">

<div class="card border-primary mb-3" style="max-width: 40rem;">
<div class="card-body">

            {% if messages %}
            <br>
            <ul class="messages">
                {% for msg in messages %}
                <li>
                    {% if msg.level > 25 %}
                    <div class="alert alert-danger" role="alert">
                        {{msg.message}}
                    </div>
                    {%else%}
                    <div class="alert alert-{{msg.level_tag}}" role="alert">
                    {{msg.message}}
                    </div>
                    {% endif%}
                </li>
                {% endfor %}
            </ul>
            {% endif %}
    {{ user_form | as_crispy_errors}}
    <h3 class="card-title">Datos Personales</h3>

      {%if user_form %}

      <!--{{ user_form.non_field_errors }}-->
      <!--{{ address_form.non_field_errors }}-->

        <form method="POST" action=""> {% csrf_token %}
            <div class="form-row">
              <div class="form-group col-md-6 mb-0">
                {{ user_form.last_name | as_crispy_field }}
              </div>

              <div class="form-group col-md-6 mb-0">
                  {{ user_form.first_name | as_crispy_field }}
              </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6 mb-0">
                    {{ user_form.gender | as_crispy_field }}
                </div>

                <div class="form-group col-md-6 mb-0">
                    {{ user_form.phone | as_crispy_field }}
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6 mb-0">
                    {{ user_form.email | as_crispy_field }}
                    {{ user_form.email | as_crispy_errors }}
                </div>
            </div>


            <div class="form-row">
              <div class="form-group col-md-6 mb-0">
                {{ address_form.country  | as_crispy_errors }}
                {{ address_form.country  | as_crispy_field }}

              </div>


            </div>

            <div class="form-row">
                <div class="form-group col-md-4 mb-0">
                  {{ address_form.state | as_crispy_errors }}
                  {{ address_form.state | as_crispy_field }}
               </div>

              <div class="form-group col-md-4 mb-0">
                {{ address_form.city  | as_crispy_errors }}
                {{ address_form.city  | as_crispy_field }}

              </div>

              <div class="form-group col-md-3 mb-0">
                  {{ address_form.zip_code | as_crispy_errors }}
                  {{ address_form.zip_code | as_crispy_field }}

              </div>
            </div>

            {{ address_form.address | as_crispy_field }}


            {{ user_form.active | as_crispy_field }}
            <h3>Redes Sociales</h3>


            {{ media_form | crispy }}

        <div align="right" class="conteiner">
            <button type="reset" class="btn btn-primary">Borrar</button>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>

        </form>

    {%endif %}

  </div>
<div class="card-footer text-muted">* Campos Obligatorios</div>
</div>
</div>

{% endblock %}

profiles/templates/profiles/users_view.html
<!DOCTYPE html>
<html>
<head>
	<title>All User</title>
</head>
<body>
    <h1>Pantalla principal de todos los User =D </h1>

    <h3>Estoy usando Template View</h3>

<table style="width:80%">
  <tr>
    <th>Full Name</th>
    <th>Email</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Country</th>
  </tr>
    {% for unUser in todos %}
        <tr>
	        <td>{{unUser}}</td>
            <td>{{unUser.email}}</td>
            <td>{{unUser.address.address}}</td>
            <td>{{unUser.address.city}}</td>
            <td>{{unUser.address.state}}</td>
            <td>{{unUser.address.country}}</td>
	    </tr>
    {% endfor %}
</table>
</body>
</html>